import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {VERCEL_ENV} from "../next.constants";
import { SpeedInsights } from '@vercel/speed-insights/next';
import { Analytics } from '@vercel/analytics/react';

import  cn  from '@/lib/utils/cn'

const inter = Inter({ subsets: ["latin"] });


const fontHeading = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-heading',
})

const fontBody = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-body',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  className={cn(
          'antialiased',
          fontHeading.variable,
          fontBody.variable
        )}>
          {children}
      </body>
      {VERCEL_ENV && (
          <>
            <Analytics />
            <SpeedInsights />
          </>
        )}
    </html>
  );
}
